version: 0.1

phases:
  install:
    commands:
      - echo no commands
  
  pre_build:
    commands:
      - echo env dump 
      - env
      - which mvn 
  build:
    commands:
      - mvn test
      - mvn package
  
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
